### ISSUE TITLE
Feature request: Configurable default size

### ISSUE THREAD

**Issue by mmgj** [williamiommi/sanity-plugin-icon-manager#18]
I'd love to be able to set a default size in the plugin configuration for all icons so that they start off at, say 50x50px instead of 20x20.

**Comment by williamiommi** [comment]
Hi @mmgj, 
Yeah, 20x20 was my generic assumption 😀. I think it could be useful to have this feature as a global plugin option, and it should not take too much time. Let me check on it in the next few days.

**Comment by williamiommi** [comment]
Hi @mmgj,

just released an update with the new global default size option.

**Comment by mmgj** [comment]
Awesome! I'll give it a go this weekend. Thanks a bunch!
